name: adipocyte-seg
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - jupyterlab=2.0.1
  - numpy=1.16.6
  - tifffile=0.14.0
  - scikit-image=0.14.2
  - opencv=3.4
  - matplotlib=3.1.3
  - tensorflow=1.15.2
  - keras=2.2.4
  - h5py=2.10.0
  - pandas=0.24.2
  - pillow=6.2.1
  - pip:
      - mahotas==1.4.9