name: adipocyte-seg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy=1.18.5
  - scipy=1.4.1
  - scikit-image=0.16.2
  - tifffile=2019.7.26
  - opencv=3.4.*
  - h5py=2.10.0
  - pandas=0.24.2
  - matplotlib=3.1.3
  - pillow=6.2.1
  - pip:
      - tensorflow==1.15.2
      - tensorflow-estimator==1.15.1
      - keras==2.2.4
      - protobuf==3.20.3     # ← add this line
      - gdown==4.7.1
